using System.Text.Json.Serialization;

namespace HarnessMcp.Contracts;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(AppConfig))]
[JsonSerializable(typeof(ServerConfig))]
[JsonSerializable(typeof(DatabaseConfig))]
[JsonSerializable(typeof(RetrievalConfig))]
[JsonSerializable(typeof(EmbeddingConfig))]
[JsonSerializable(typeof(LoggingConfig))]
[JsonSerializable(typeof(MonitoringConfig))]
[JsonSerializable(typeof(FeatureConfig))]
[JsonSerializable(typeof(HealthProbeResult))]
[JsonSerializable(typeof(MonitorEventDto))]
[JsonSerializable(typeof(MonitorBatchDto))]
[JsonSerializable(typeof(MonitorSnapshotDto))]
[JsonSerializable(typeof(MonitorServerSummaryDto))]
[JsonSerializable(typeof(ServerInfoResponse))]
[JsonSerializable(typeof(FeatureFlagsDto))]
[JsonSerializable(typeof(SchemaSetDto))]
[JsonSerializable(typeof(SearchKnowledgeRequest))]
[JsonSerializable(typeof(SearchKnowledgeResponse))]
[JsonSerializable(typeof(SearchKnowledgeDiagnosticsDto))]
[JsonSerializable(typeof(KnowledgeCandidateDto))]
[JsonSerializable(typeof(EvidenceDto))]
[JsonSerializable(typeof(ScopeFilterDto))]
[JsonSerializable(typeof(RetrieveMemoryByChunksRequest))]
[JsonSerializable(typeof(RetrieveMemoryByChunksResponse))]
[JsonSerializable(typeof(RetrievalChunkDto))]
[JsonSerializable(typeof(SimilarCaseShapeDto))]
[JsonSerializable(typeof(RequirementIntentDto))]
[JsonSerializable(typeof(ChunkSearchProfileDto))]
[JsonSerializable(typeof(ChunkBucketDto))]
[JsonSerializable(typeof(ChunkRetrievalResultDto))]
[JsonSerializable(typeof(ContextPackSectionDto))]
[JsonSerializable(typeof(ContextPackDiagnosticsDto))]
[JsonSerializable(typeof(MergedKnowledgeItemDto))]
[JsonSerializable(typeof(MergeRetrievalResultsRequest))]
[JsonSerializable(typeof(MergeRetrievalResultsResponse))]
[JsonSerializable(typeof(BuildMemoryContextPackRequest))]
[JsonSerializable(typeof(BuildMemoryContextPackResponse))]
[JsonSerializable(typeof(GetKnowledgeItemRequest))]
[JsonSerializable(typeof(GetKnowledgeItemResponse))]
[JsonSerializable(typeof(GetRelatedKnowledgeRequest))]
[JsonSerializable(typeof(GetRelatedKnowledgeResponse))]
[JsonSerializable(typeof(RetrievalClass))]
[JsonSerializable(typeof(QueryKind))]
[JsonSerializable(typeof(AuthorityLevel))]
[JsonSerializable(typeof(KnowledgeStatus))]
[JsonSerializable(typeof(ChunkType))]
[JsonSerializable(typeof(RelationType))]
[JsonSerializable(typeof(TransportMode))]
[JsonSerializable(typeof(MonitorEventKind))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<KnowledgeCandidateDto>))]
[JsonSerializable(typeof(List<EvidenceDto>))]
[JsonSerializable(typeof(List<RetrievalClass>))]
[JsonSerializable(typeof(List<RelationType>))]
[JsonSerializable(typeof(List<ChunkType>))]
[JsonSerializable(typeof(List<RetrievalChunkDto>))]
[JsonSerializable(typeof(List<ChunkRetrievalResultDto>))]
[JsonSerializable(typeof(List<MergedKnowledgeItemDto>))]
[JsonSerializable(typeof(List<KnowledgeSegmentDto>))]
[JsonSerializable(typeof(List<RelatedKnowledgeDto>))]
[JsonSerializable(typeof(List<MonitorEventDto>))]
public partial class AppJsonSerializerContext : JsonSerializerContext;
